sudo: false
language: c

dist: trusty

matrix:
  include:
    - os: linux
      env: NIM_COMPILE_TO_CPP=false

    - os: osx
      env: NIM_COMPILE_TO_CPP=false

    - os: osx
      env: NIM_COMPILE_TO_CPP=true

# To allow failures for a failing configuration, use something like:
#  allow_failures:
#    - env: NIM_COMPILE_TO_CPP=true
#    - os: osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.0j-1~deb9u1_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i libssl1.1_1.1.0j-1~deb9u1_amd64.deb; fi
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - export PATH=$(pwd)/bin${PATH:+:$PATH}
  - echo PATH:${PATH}

script:
  - nim c koch
  - ./koch runCI

before_deploy:
  # Make https://nim-lang.github.io/Nim work the same as https://nim-lang.github.io/Nim/overview.html
  - cp -f ./doc/html/overview.html ./doc/html/index.html
deploy:                         # https://nim-lang.github.io/Nim
  provider: pages
  # local-dir *has* to be a relative path from the repo root.
  local-dir: "doc/html"
  skip-cleanup: true
  github-token: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  on:
    branch: devel
